### ISSUE TITLE
Add wait after Redis Subscribe receives error so if error continues it doesn't spam the log file

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-messaging#156]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
This feature request is for Redis Subscribe

### Description [**REQUIRED**]
Currently the code simply logs the error and continues to try to read for connection again. If the Redis instance has been restarted, the log file will fill up with connection error messages until Redis instance responds again.

### Describe the solution you'd like
Add an escalating wait after the error is logged and before continuing. Simple error count used to increase wait for repeated errors that is cleared once a successful message has been received.

### Describe alternatives you've considered
Leave it how it is.

**Comment by cloudxxx8** [comment]
this issue can still be reproduced in core-data and app-service-configurable

**Comment by cloudxxx8** [comment]
The reproduce steps provided by @farshidtz :
Terminal 1:
$ snap install edgexfoundry --edge
edgexfoundry (edge) 2.3.0-dev.38 from Canonical✓ installed
Terminal 2:
snap logs -f edgexfoundry
back to terminal 1:
$ snap restart edgexfoundry
$ snap start edgexfoundry.security-secretstore-setup
Check the logs in Terminal 2.

**Comment by farshidtz** [comment]
I turns out that the errors were indeed from an older version.

The 2.3.0-dev.38 snap which I used for testing [includes the 2.2.0 (latest/stable) app-service-configurable ](https://github.com/edgexfoundry/edgex-go/blob/e3ca38a5709b6fd134cd3d7a24fe413a337b80c3/snap/snapcraft.yaml#L771) which doesn't have this fix.

In another test, the errors were coming during an upgrade of `edgexfoundry` snap from 2.2.0 to 2.3.0-dev.35.

@cloudxxx8 please re-close.
