### ISSUE TITLE
run edgex with nats messagebus in docker get “already connected to NATS” error

### ISSUE THREAD

**Issue by zouyuxuan** [edgexfoundry/go-mod-messaging#271]
I use the edgex-compose project to generate the docker-compose.ymal file, the generation command is` cd compose-builder&& make gen no-secty nats-bus ds-virtual`, the command to generate the docker image is `cd edgex-go&& make docker-nats`. After running docker-compose up, the edgex-app-rules-engine container has been restarting. Check the logs and find that the application in the edgex-app-rules-engine container has connected to the nats service twice, resulting in an error“already connected to NATS”when connecting for the second time。
## 🌍  Your Environment
**Deployment Environment:** ubuntu 20.04 ,docker 23.0.1

**EdgeX Version [**REQUIRED**]:** 3.0.0

**Comment by cloudxxx8** [comment]
@zouyuxuan please use English to describe your problem because most people in this community are English speaker.  Using English could get more help.
Also, please don't just paste your log with the context.  Please fill out all the section in the issue template, including version, config, and steps, or we can't help you.

**Comment by lenny-intel** [comment]
@zouyuxuan you also have to run `make docker-nats` for `app-service-configurable` and for `device-virtual`. I assume you did this?

Also please provide the log file for edgex-app-rules-engine container

**Comment by lenny-intel** [comment]
@zouyuxuan , have you been able to resolve the error? If so, please close this issue.
