### ISSUE TITLE
Remove Attribution.txt file

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-messaging#32]
The Attribution.txt file is not needed since this is a module and doesn't create a direct artifact that is published.

**Comment by jpwhitemn** [comment]
@lenny-intel - still a Fuji release item?  Label Geneva?

**Comment by michaelestrin** [comment]
I wonder if we shouldn't ensure that modules specify their dependencies so that we can easily reconcile dependencies in the attribution.txt file for those services that use these modules.  It doesn't hurt to have this file here but we should be consistent across the modules; i.e. either have them or not (and if we do, enforce them in the build process as we do with the services).  What do you think @lenny-intel?

**Comment by lenny-intel** [comment]
@michaelestrin , been going back and forth on this one. At the last minute we added it back to the app-functions-sdk-go for fuji. @jpwhitemn,  I think we need discuss in the Arch meeting to come to a group decision.

**Comment by lenny-intel** [comment]
Attribution.txt file not in any of the "modules" repos.
