### ISSUE TITLE
Add NATS implementation for MessageClient interface

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/go-mod-messaging#37]
Create NATS implementation of the MessageClient interface.

**Comment by AlexCuse** [comment]
This might be the oldest issue I've ever replied to.  But I have been working on a client for NATS JetStream and I think the way nats.go is written allows for this pretty easily: https://github.com/edgexfoundry/go-mod-messaging/pull/137

**Comment by AlexCuse** [comment]
I haven't dug all the way in but tried again this morning and it actually does seem to work, I may have fixed something while debugging the jetstream stuff.  Have not tested any auth yet.

Publishing using nats-core from device services and using higher JetStream QOS northbound from there is the use case I had in mind for it but what I've seen so far is they talk to each other pretty seamlessly so you can kind of mix and match.  The only limitation is that its configured at a service level not the individual hosts - so you can't have e.g an app service with a jetstream subscription publish using nats-core.

**Comment by AlexCuse** [comment]
Since there wasn't really any rationale given for inclusion of a NATS implementation in the original ticket but I can add what drew me to it:

1. lightweight protocol with potential for on-device use
2. ability to use common messaging infrastructure at all levels of stack
3. protocol-level metadata which allows 'native' conveyance of the EdgeX message envelope.
4. flexible deployment options for HA in some settings

Beyond that, JetStream adds:

1. Durable messaging / elevated QoS
2. limited MQTT support (https://docs.nats.io/running-a-nats-service/configuration/mqtt)
3. (currently experimental) key-value store that could potentially be used to add persistent backing for the app service store-forward loop

Happy to elaborate further on any of the above.

**Comment by AlexCuse** [comment]
Sure Lenny it adds 

- github.com/nats-io/nats.go v1.13 **(Apache 2)**
- github.com/hashicorp/go-multierror v1.1.1 **(MPL-2, I believe already an indirect dependency in both SDKs)**

Multierror is easy to get rid of if it helps.

There are also some indirect dependencies I will dig further into soon.

**Comment by lenny-intel** [comment]
NATS included for Levski during planning as a opt-in build only option. i.e. default builds do not include it. One must rebuild services, that uses the MessageBus, with a opt-in build flag.
