### ISSUE TITLE
Replace ZeroMQ library for a pure golang ZeroMQ library

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/go-mod-messaging#73]
Currently the ZeroMQ library forces EdgeX to use cgo, but there are [several reasons](https://dave.cheney.net/2016/01/18/cgo-is-not-go) to use a pure golang ZeroMQ library instead of cgo.

Using a pure golang ZeroMQ will remove the dependency of external libraries, resolving issues like #54, making easier to work with EdgeX, also making possible to cross compile, and several other benefits.

EdgeX is using [pebbe/zmq4](https://github.com/pebbe/zmq4), which forces the use of cgo. But this library can be replaced by [go-zeromq/zmq4](https://github.com/go-zeromq/zmq4), which is a pure golang ZeroMQ library.

**Comment by cloudxxx8** [comment]
@jduranf thanks for the suggestion.
since it states [WIP] Pure-Go implementation of ZeroMQ-4, do you know whether it is ready to be used in production?

**Comment by jduranf** [comment]
If I'm not wrong, the WIP is because not all ZeroMQ features are implemented. But the main features used by EdgeX, which are PUB/SUB, are implemented:
https://github.com/go-zeromq/zmq4/issues/9

Anyway, the main developer is @sbinet, and maybe we can ask him if the library is ready for production.

**Comment by sbinet** [comment]
the push/pull and pub/sub sockets are ok.
I've used them for a CERN application and they are also used in gophernotes.

but "production" is a vague term, w/o explicit working points and expected performances.
I must admit I haven't put time into properly describing the performances of go-zmq/zmq4: "it was working for me/my use cases (TM)".

**Comment by jpwhitemn** [comment]
Per Ireland Planning Meeting, this issue is in scope for Ireland release.
"Paper Study" shows that alternative suggestion (go-zeromq/zmq4)  would be suitable replacement
Release tags: 15
Contributors:  7
Last Commit:  27 days ago
License:  BSD-3
Stars:  170
Watchers:  16
Forks:  32
GoDoc Imports: 19 packages
GoDoc Imported By:  11 packages
Go Dock Updated:  25 days ago

EdgeX PM to make API comparison and check for viability of replacement library with current pebbe/zmp4.

**Comment by lenny-intel** [comment]
Note trivial switching modules as the APIs are quite different so more time will be needed to understand the `go-zmq/zmq4` and how to rewrite our ZMQ implementation using it.

**Comment by jpwhitemn** [comment]
Should not cause breaking changes if replaced so a target for Jakarta??

**Comment by lenny-intel** [comment]
> Should not cause breaking changes if replaced so a target for Jakarta??

Correct, internal only

**Comment by liamylian** [comment]
Since Edgex Foundry 2.0, Redis is the default Messaging Bus, why not move ZeroMQ support out of this library. Any services (such as core services) that need ZeroMQ support option, could import ZeroMQ adapter independently. But other services (application services, device services), could choose weather support ZeroMQ or not. Finally, we would have the option to get rid of tricky CGO stuff.

**Comment by cloudxxx8** [comment]
I think so.  We can discuss in the Core WG meeting.

**Comment by lenny-intel** [comment]
Nope, we can't until next major release. We have declared `ZeroMQ` as deprecated in Ireland and to be removed in future release, which has to be a major release.

**Comment by JamesKButcher** [comment]
ZeroMQ is deprecated in Ireland and will be removed in future. No more development planned here
